# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


booksstore_api = Blueprint('booksstore_api', __name__)


@booksstore_api.route('/books', methods=['GET'])
def books_get():
    """
    It is handler for GET /books
    """
    return handlers.books_getHandler()


@booksstore_api.route('/books', methods=['POST'])
def books_post():
    """
    It is handler for POST /books
    """
    return handlers.books_postHandler()


@booksstore_api.route('/books/<bookId>', methods=['GET'])
def books_byBookId_get(bookId):
    """
    Retrieve book-related information.
    It is handler for GET /books/<bookId>
    """
    return handlers.books_byBookId_getHandler(bookId)


@booksstore_api.route('/books/<bookId>', methods=['PUT'])
def books_byBookId_put(bookId):
    """
    Update book information.
    It is handler for PUT /books/<bookId>
    """
    return handlers.books_byBookId_putHandler(bookId)


@booksstore_api.route('/books/<bookId>', methods=['DELETE'])
def books_byBookId_delete(bookId):
    """
    Remove book from the Store.
    It is handler for DELETE /books/<bookId>
    """
    return handlers.books_byBookId_deleteHandler(bookId)
